# ===============================================
# PostgreSQL Database Configuration
# ===============================================

app:
  database:
    type: postgresql
    host: ${DATABASE_HOST:localhost}
    port: ${DATABASE_PORT:5432}
    name: ${DATABASE_NAME:authdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    pool:
      maximum-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    options:
      create-database-if-not-exist: true
      show-sql: false
      format-sql: false

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}  # Options: create, create-drop, update, validate, none
    show-sql: ${app.database.options.show-sql}
    properties:
      hibernate:
        format_sql: ${app.database.options.format-sql}
        jdbc:
          lob:
            non_contextual_creation: true

# PostgreSQL specific environment variables
# Set these in your environment or .env file:
# DATABASE_HOST=localhost
# DATABASE_PORT=5432
# DATABASE_NAME=authdb
# DATABASE_USERNAME=your_username
# DATABASE_PASSWORD=your_password

# Sample Docker command to run PostgreSQL:
# docker run --name postgres-auth \
#   -e POSTGRES_DB=authdb \
#   -e POSTGRES_USER=postgres \
#   -e POSTGRES_PASSWORD=password \
#   -p 5432:5432 \
#   -d postgres:13

# Sample SQL commands to create database and user:
# CREATE DATABASE authdb;
# CREATE USER authuser WITH ENCRYPTED PASSWORD 'password';
# GRANT ALL PRIVILEGES ON DATABASE authdb TO authuser;
